{
 "title": "Codehub services statuses",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "200 codehub statuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(codehub_services_hits{status=\"200\"}[5m]))"
    }
   ]
  },
  {
   "title": "500 codehub statuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(codehub_services_hits{status=\"500\"}[5m]))"
    }
   ]
  },
  {
   "title": "404 codehub statuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(codehub_services_hits{status=\"401\"}[5m]))"
    }
   ]
  },
  {
   "title": "403 codehub statuses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(codehub_services_hits{status=\"403\"}[5m]))"
    }
   ]
  }
 ]
}