// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mockCodehub is a generated GoMock package.
package mockCodehub

import (
	models "github.com/go-park-mail-ru/2020_1_GitBreakers/internal/pkg/models"
	git "github.com/go-park-mail-ru/2020_1_GitBreakers/internal/pkg/models/git"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUCCodeHubI is a mock of UCCodeHubI interface
type MockUCCodeHubI struct {
	ctrl     *gomock.Controller
	recorder *MockUCCodeHubIMockRecorder
}

// MockUCCodeHubIMockRecorder is the mock recorder for MockUCCodeHubI
type MockUCCodeHubIMockRecorder struct {
	mock *MockUCCodeHubI
}

// NewMockUCCodeHubI creates a new mock instance
func NewMockUCCodeHubI(ctrl *gomock.Controller) *MockUCCodeHubI {
	mock := &MockUCCodeHubI{ctrl: ctrl}
	mock.recorder = &MockUCCodeHubIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUCCodeHubI) EXPECT() *MockUCCodeHubIMockRecorder {
	return m.recorder
}

// ModifyStar mocks base method
func (m *MockUCCodeHubI) ModifyStar(star models.Star) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyStar", star)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyStar indicates an expected call of ModifyStar
func (mr *MockUCCodeHubIMockRecorder) ModifyStar(star interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyStar", reflect.TypeOf((*MockUCCodeHubI)(nil).ModifyStar), star)
}

// GetStarredRepos mocks base method
func (m *MockUCCodeHubI) GetStarredRepos(userID, limit, offset int64) (models.RepoSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarredRepos", userID, limit, offset)
	ret0, _ := ret[0].(models.RepoSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarredRepos indicates an expected call of GetStarredRepos
func (mr *MockUCCodeHubIMockRecorder) GetStarredRepos(userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarredRepos", reflect.TypeOf((*MockUCCodeHubI)(nil).GetStarredRepos), userID, limit, offset)
}

// CreateIssue mocks base method
func (m *MockUCCodeHubI) CreateIssue(issue models.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIssue indicates an expected call of CreateIssue
func (mr *MockUCCodeHubIMockRecorder) CreateIssue(issue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockUCCodeHubI)(nil).CreateIssue), issue)
}

// UpdateIssue mocks base method
func (m *MockUCCodeHubI) UpdateIssue(issue models.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIssue", issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIssue indicates an expected call of UpdateIssue
func (mr *MockUCCodeHubIMockRecorder) UpdateIssue(issue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIssue", reflect.TypeOf((*MockUCCodeHubI)(nil).UpdateIssue), issue)
}

// CloseIssue mocks base method
func (m *MockUCCodeHubI) CloseIssue(issueID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIssue", issueID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseIssue indicates an expected call of CloseIssue
func (mr *MockUCCodeHubIMockRecorder) CloseIssue(issueID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIssue", reflect.TypeOf((*MockUCCodeHubI)(nil).CloseIssue), issueID, userID)
}

// GetIssuesList mocks base method
func (m *MockUCCodeHubI) GetIssuesList(repoID, userID, limit, offset int64) (models.IssuesSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssuesList", repoID, userID, limit, offset)
	ret0, _ := ret[0].(models.IssuesSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssuesList indicates an expected call of GetIssuesList
func (mr *MockUCCodeHubIMockRecorder) GetIssuesList(repoID, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssuesList", reflect.TypeOf((*MockUCCodeHubI)(nil).GetIssuesList), repoID, userID, limit, offset)
}

// GetIssue mocks base method
func (m *MockUCCodeHubI) GetIssue(issueID, userID int64) (models.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssue", issueID, userID)
	ret0, _ := ret[0].(models.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssue indicates an expected call of GetIssue
func (mr *MockUCCodeHubIMockRecorder) GetIssue(issueID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssue", reflect.TypeOf((*MockUCCodeHubI)(nil).GetIssue), issueID, userID)
}

// GetNews mocks base method
func (m *MockUCCodeHubI) GetNews(repoID, userID, limit, offset int64) (models.NewsSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNews", repoID, userID, limit, offset)
	ret0, _ := ret[0].(models.NewsSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNews indicates an expected call of GetNews
func (mr *MockUCCodeHubIMockRecorder) GetNews(repoID, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNews", reflect.TypeOf((*MockUCCodeHubI)(nil).GetNews), repoID, userID, limit, offset)
}

// GetUserStaredList mocks base method
func (m *MockUCCodeHubI) GetUserStaredList(repoID, limit, offset int64) (models.UserSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStaredList", repoID, limit, offset)
	ret0, _ := ret[0].(models.UserSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStaredList indicates an expected call of GetUserStaredList
func (mr *MockUCCodeHubIMockRecorder) GetUserStaredList(repoID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStaredList", reflect.TypeOf((*MockUCCodeHubI)(nil).GetUserStaredList), repoID, limit, offset)
}

// Search mocks base method
func (m *MockUCCodeHubI) Search(query, params string, limit, offset, userID int64) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", query, params, limit, offset, userID)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search
func (mr *MockUCCodeHubIMockRecorder) Search(query, params, limit, offset, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockUCCodeHubI)(nil).Search), query, params, limit, offset, userID)
}

// CreatePL mocks base method
func (m *MockUCCodeHubI) CreatePL(request models.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePL", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePL indicates an expected call of CreatePL
func (mr *MockUCCodeHubIMockRecorder) CreatePL(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePL", reflect.TypeOf((*MockUCCodeHubI)(nil).CreatePL), request)
}

// GetPLIn mocks base method
func (m *MockUCCodeHubI) GetPLIn(repo git.Repository, limit, offset int64) (models.PullReqSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPLIn", repo, limit, offset)
	ret0, _ := ret[0].(models.PullReqSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPLIn indicates an expected call of GetPLIn
func (mr *MockUCCodeHubIMockRecorder) GetPLIn(repo, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPLIn", reflect.TypeOf((*MockUCCodeHubI)(nil).GetPLIn), repo, limit, offset)
}

// GetPLOut mocks base method
func (m *MockUCCodeHubI) GetPLOut(repo git.Repository, limit, offset int64) (models.PullReqSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPLOut", repo, limit, offset)
	ret0, _ := ret[0].(models.PullReqSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPLOut indicates an expected call of GetPLOut
func (mr *MockUCCodeHubIMockRecorder) GetPLOut(repo, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPLOut", reflect.TypeOf((*MockUCCodeHubI)(nil).GetPLOut), repo, limit, offset)
}

// ApprovePL mocks base method
func (m *MockUCCodeHubI) ApprovePL(pl models.PullRequest, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePL", pl, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApprovePL indicates an expected call of ApprovePL
func (mr *MockUCCodeHubIMockRecorder) ApprovePL(pl, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePL", reflect.TypeOf((*MockUCCodeHubI)(nil).ApprovePL), pl, userID)
}

// ClosePL mocks base method
func (m *MockUCCodeHubI) ClosePL(pl models.PullRequest, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosePL", pl, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClosePL indicates an expected call of ClosePL
func (mr *MockUCCodeHubIMockRecorder) ClosePL(pl, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosePL", reflect.TypeOf((*MockUCCodeHubI)(nil).ClosePL), pl, userID)
}

// GetAllMRUser mocks base method
func (m *MockUCCodeHubI) GetAllMRUser(userID int64) (models.PullReqSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMRUser", userID)
	ret0, _ := ret[0].(models.PullReqSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMRUser indicates an expected call of GetAllMRUser
func (mr *MockUCCodeHubIMockRecorder) GetAllMRUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMRUser", reflect.TypeOf((*MockUCCodeHubI)(nil).GetAllMRUser), userID)
}
