// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package git

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE2537327DecodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit(in *jlexer.Lexer, out *FileCommitted) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "file_info":
			easyjsonE2537327DecodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit1(in, &out.FileInfo)
		case "content":
			out.Content = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE2537327EncodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit(out *jwriter.Writer, in FileCommitted) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"file_info\":"
		out.RawString(prefix[1:])
		easyjsonE2537327EncodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit1(out, in.FileInfo)
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileCommitted) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE2537327EncodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileCommitted) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE2537327EncodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileCommitted) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE2537327DecodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileCommitted) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE2537327DecodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit(l, v)
}
func easyjsonE2537327DecodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit1(in *jlexer.Lexer, out *FileInCommit) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "file_type":
			out.FileType = string(in.String())
		case "file_mode":
			out.FileMode = string(in.String())
		case "file_size":
			out.FileSize = int64(in.Int64())
		case "is_binary":
			out.IsBinary = bool(in.Bool())
		case "content_type":
			out.ContentType = string(in.String())
		case "entry_hash":
			out.EntryHash = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE2537327EncodeGithubComGoParkMailRu20201GitBreakersInternalPkgModelsGit1(out *jwriter.Writer, in FileInCommit) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"file_type\":"
		out.RawString(prefix)
		out.String(string(in.FileType))
	}
	{
		const prefix string = ",\"file_mode\":"
		out.RawString(prefix)
		out.String(string(in.FileMode))
	}
	{
		const prefix string = ",\"file_size\":"
		out.RawString(prefix)
		out.Int64(int64(in.FileSize))
	}
	{
		const prefix string = ",\"is_binary\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBinary))
	}
	{
		const prefix string = ",\"content_type\":"
		out.RawString(prefix)
		out.String(string(in.ContentType))
	}
	{
		const prefix string = ",\"entry_hash\":"
		out.RawString(prefix)
		out.String(string(in.EntryHash))
	}
	out.RawByte('}')
}
