global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'codehub'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'gitserver'
      static_configs:
        - targets: ['host.docker.internal:5000']

  - job_name: 'system'
      static_configs:
        - targets: ['host.docker.internal:9100']
