// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	git "github.com/go-park-mail-ru/2020_1_GitBreakers/internal/pkg/models/git"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockUseCase) Create(userID int, repos *git.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, repos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockUseCaseMockRecorder) Create(userID, repos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUseCase)(nil).Create), userID, repos)
}

// GetRepo mocks base method
func (m *MockUseCase) GetRepo(userName, repoName string, requestUserID *int) (git.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo", userName, repoName, requestUserID)
	ret0, _ := ret[0].(git.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepo indicates an expected call of GetRepo
func (mr *MockUseCaseMockRecorder) GetRepo(userName, repoName, requestUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockUseCase)(nil).GetRepo), userName, repoName, requestUserID)
}

// GetRepoList mocks base method
func (m *MockUseCase) GetRepoList(userName string, requestUserID *int) ([]git.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoList", userName, requestUserID)
	ret0, _ := ret[0].([]git.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoList indicates an expected call of GetRepoList
func (mr *MockUseCaseMockRecorder) GetRepoList(userName, requestUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoList", reflect.TypeOf((*MockUseCase)(nil).GetRepoList), userName, requestUserID)
}

// GetBranchList mocks base method
func (m *MockUseCase) GetBranchList(requestUserID *int, userName, repoName string) ([]git.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchList", requestUserID, userName, repoName)
	ret0, _ := ret[0].([]git.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranchList indicates an expected call of GetBranchList
func (mr *MockUseCaseMockRecorder) GetBranchList(requestUserID, userName, repoName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchList", reflect.TypeOf((*MockUseCase)(nil).GetBranchList), requestUserID, userName, repoName)
}

// FilesInCommitByPath mocks base method
func (m *MockUseCase) FilesInCommitByPath(requset git.FilesCommitRequest, requesrUserID *int) ([]git.FileInCommit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesInCommitByPath", requset, requesrUserID)
	ret0, _ := ret[0].([]git.FileInCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesInCommitByPath indicates an expected call of FilesInCommitByPath
func (mr *MockUseCaseMockRecorder) FilesInCommitByPath(requset, requesrUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesInCommitByPath", reflect.TypeOf((*MockUseCase)(nil).FilesInCommitByPath), requset, requesrUserID)
}

// GetCommitsByCommitHash mocks base method
func (m *MockUseCase) GetCommitsByCommitHash(params git.CommitRequest, requestUserID *int) ([]git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsByCommitHash", params, requestUserID)
	ret0, _ := ret[0].([]git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitsByCommitHash indicates an expected call of GetCommitsByCommitHash
func (mr *MockUseCaseMockRecorder) GetCommitsByCommitHash(params, requestUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsByCommitHash", reflect.TypeOf((*MockUseCase)(nil).GetCommitsByCommitHash), params, requestUserID)
}

// GetCommitsByBranchName mocks base method
func (m *MockUseCase) GetCommitsByBranchName(userLogin, repoName, branchName string, offset, limit int, requestUserID *int) ([]git.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsByBranchName", userLogin, repoName, branchName, offset, limit, requestUserID)
	ret0, _ := ret[0].([]git.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitsByBranchName indicates an expected call of GetCommitsByBranchName
func (mr *MockUseCaseMockRecorder) GetCommitsByBranchName(userLogin, repoName, branchName, offset, limit, requestUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsByBranchName", reflect.TypeOf((*MockUseCase)(nil).GetCommitsByBranchName), userLogin, repoName, branchName, offset, limit, requestUserID)
}

// GetFileByPath mocks base method
func (m *MockUseCase) GetFileByPath(params git.FilesCommitRequest, requestUserID *int) (git.FileCommitted, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByPath", params, requestUserID)
	ret0, _ := ret[0].(git.FileCommitted)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByPath indicates an expected call of GetFileByPath
func (mr *MockUseCaseMockRecorder) GetFileByPath(params, requestUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByPath", reflect.TypeOf((*MockUseCase)(nil).GetFileByPath), params, requestUserID)
}
