on:
  push:
    branches:
      - master
      - easy_dev
      - gitrepo
  pull_request:
    branches: [ master ]
jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.14.x
#
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Test
#        run: go test ./internal/pkg/session/repository/redis/
#
#      - name: Build server
#        run: go build -o server ./cmd/server/main.go
#
#      - name: Build user
#        run: go build -o user ./cmd/user/main.go
#
#      - name: Build auth
#        run: go build -o auth ./cmd/auth/main.go
#
#      - name: Build news
#        run: go build -o news ./cmd/news/main.go
#
#      - name: Build gitserver
#        run: go build -o gitserver ./cmd/gitserver/main.go

#      - name: Upload build server
#          uses: actions/upload-artifact@v1
#          with:
#            name: server
#            path: ./server
#
#      - name: Upload build user
#          uses: actions/upload-artifact@v1
#          with:
#            name: user
#            path: ./user
#
#      - name: Upload build auth
#          uses: actions/upload-artifact@v1
#          with:
#            name: auth
#            path: ./auth
#
#      - name: Upload build news
#          uses: actions/upload-artifact@v1
#          with:
#            name: news
#            path: ./news
#
#      - name: Upload build gitserver
#          uses: actions/upload-artifact@v1
#          with:
#            name: gitserver
#            path: ./gitserver

  deploy:
    runs-on: ubuntu-latest
#    needs: build
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"

    - name: Update prod
      uses: appleboy/ssh-action@master
      env:
        CURR_BRANCH: ${BRANCH_NAME}
      with:
        host: 89.208.198.186
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/CodeHub
          echo `${CURR_BRANCH}`
          git checkout ${CURR_BRANCH}
          git pull origin easy_dev
          /bin/bash run.sh
#          лул


