on: [push, pull_request]
name: Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./internal/pkg/session/repository/redis/

      - name: Build server
        run: go build -o server ./cmd/server/main.go

      - name: Build user
        run: go build -o user ./cmd/user/main.go

      - name: Build auth
        run: go build -o auth ./cmd/auth/main.go

      - name: Build news
        run: go build -o news ./cmd/news/main.go

      - name: Build gitserver
        run: go build -o gitserver ./cmd/gitserver/main.go
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
