on:
  push:
    branches:
      - master
      - easy_dev
      - gitrepo
#  pull_request:
#    branches: [ master ]
jobs:
#  tests:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: tests
#        run: go test -coverpkg=./internal/... ./internal/... -coverprofile cover.out && go tool cover -func cover.out | grep total
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.14.x
#
#      - name: Checkout code
#        uses: actions/checkout@v2

#
#      - name: Build server
#        run: go build -o server ./cmd/server/main.go
#
#      - name: Build user
#        run: go build -o user ./cmd/user/main.go
#
#      - name: Build auth
#        run: go build -o auth ./cmd/auth/main.go
#
#      - name: Build news
#        run: go build -o news ./cmd/news/main.go
#
#      - name: Build gitserver
#        run: go build -o gitserver ./cmd/gitserver/main.go
  deploy:
    runs-on: ubuntu-latest
#    needs: build
    steps:
    - name: Update prod
      uses: appleboy/ssh-action@master
      env:
        CURR_BRANCH: ${{ github.ref }}
      with:
        host: 89.208.198.186
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script_stop: true
        envs: CURR_BRANCH
        script: |
          cd /home/ubuntu/CodeHub
          git checkout ${CURR_BRANCH##*/}
          git pull origin ${CURR_BRANCH##*/}
          ./run.sh


